C++ requires a type specifier for all declarations
src/2d/toy/phantom_cmd.cpp:25:1: error: C++ requires a type specifier for all declarations
main(int argc, char* argv[]) {
^